# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18c0-Q5xccoHlu5dd_ucZgN7IEsktHGH3
"""

def test_model(img_path, model):

    """ 
    path : test image folder path
    model : model instantiation
    
    DRIVE SHOULD BE MOUNTED
    
    """
    directory = '/content/drive/Test'
    os.chdir(directory)
    i=0


    plt.figure(figsize = (15,15))
    test_img = glob.glob(img_path + '/*.jpg')
    test_img_slice = tf.data.Dataset.from_tensor_slices([img for img in test_img]).map(lambda x: load_image(x))
    test = tf.data.Dataset.zip((test_img_slice))
    
    for img in test:
        pred = model(img)
        plt.imshow(pred)
        filename = 'Test-' + str(i) + '.jpg'
        cv2.imwrite(filename, pred) 
        i+=1
        

    plt.show()

